# Geopolitical Event Dataset Loading and Exploring

- Objective:
Explore datasets that downlode from GDELT database of major geopolitical events that may affect
Indian stock market sectors.

- Period:
2018-01-01 to 2026-06-01

In [2]:
import pandas as pd
import numpy as np

### 1. **Load all the GDELT data sets**

In [3]:
daily = pd.read_csv(r'E:\BDA\Summer 2026\Data\raw_data\gdelt_daily_2018_2026.csv', parse_dates=['Date'])
master = pd.read_csv(r'E:\BDA\Summer 2026\Data\raw_data\gdelt_master_features.csv', parse_dates=['Date'])
conflict = pd.read_csv(r'E:\BDA\Summer 2026\Data\raw_data\gdelt_country_conflict.csv', parse_dates=['Date'])
events = pd.read_csv(r'E:\BDA\Summer 2026\Data\raw_data\gdelt_country_events.csv', parse_dates=['Date'])
tone = pd.read_csv(r'E:\BDA\Summer 2026\Data\raw_data\gdelt_country_tone.csv', parse_dates=['Date'])

In [4]:
df = pd.read_csv(r"E:\BDA\Summer 2026\Data\raw_data\bquxjob_4c374645_19ef5447a48.csv")

# 2. **Analyize**

### 2.1 **Analyize df**

In [7]:
df.sample(5)

,GLOBALEVENTID,SQLDATE,MonthYear,Year,FractionDate,Actor1Code,Actor1Name,Actor1CountryCode,Actor1KnownGroupCode,Actor1EthnicCode,...,ActionGeo_Type,ActionGeo_FullName,ActionGeo_CountryCode,ActionGeo_ADM1Code,ActionGeo_ADM2Code,ActionGeo_Lat,ActionGeo_Long,ActionGeo_FeatureID,DATEADDED,SOURCEURL
5,1310404351,20260623,202606,2026,2026.474,CHE,SWITZ,CHE,NaN,NaN,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20260623161500,https://www.wthitv.com:443/2026/06/23/linton-m...
0,1310404008,20250623,202506,2025,2025.474,CVL,RESIDENTS,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20260623161500,https://www.thestar.com.my/news/nation/2026/06...
4,1310404316,20260623,202606,2026,2026.474,BUS,EMPLOYER,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20260623161500,https://indianexpress.com/article/cities/banga...
2,1310404262,20260623,202606,2026,2026.474,BGD,PATUAKHALI,BGD,NaN,NaN,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20260623161500,https://www.bssnews.net/district/398976
7,1310404387,20260623,202606,2026,2026.474,COP,POLICE,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20260623161500,https://www.thehindu.com/news/national/karnata...

In [10]:
print(df.columns.tolist())
print(df.shape)

['GLOBALEVENTID', 'SQLDATE', 'MonthYear', 'Year', 'FractionDate', 'Actor1Code', 'Actor1Name', 'Actor1CountryCode', 'Actor1KnownGroupCode', 'Actor1EthnicCode', 'Actor1Religion1Code', 'Actor1Religion2Code', 'Actor1Type1Code', 'Actor1Type2Code', 'Actor1Type3Code', 'Actor2Code', 'Actor2Name', 'Actor2CountryCode', 'Actor2KnownGroupCode', 'Actor2EthnicCode', 'Actor2Religion1Code', 'Actor2Religion2Code', 'Actor2Type1Code', 'Actor2Type2Code', 'Actor2Type3Code', 'IsRootEvent', 'EventCode', 'EventBaseCode', 'EventRootCode', 'QuadClass', 'GoldsteinScale', 'NumMentions', 'NumSources', 'NumArticles', 'AvgTone', 'Actor1Geo_Type', 'Actor1Geo_FullName', 'Actor1Geo_CountryCode', 'Actor1Geo_ADM1Code', 'Actor1Geo_ADM2Code', 'Actor1Geo_Lat', 'Actor1Geo_Long', 'Actor1Geo_FeatureID', 'Actor2Geo_Type', 'Actor2Geo_FullName', 'Actor2Geo_CountryCode', 'Actor2Geo_ADM1Code', 'Actor2Geo_ADM2Code', 'Actor2Geo_Lat', 'Actor2Geo_Long', 'Actor2Geo_FeatureID', 'ActionGeo_Type', 'ActionGeo_FullName', 'ActionGeo_CountryCode', 'ActionGeo_ADM1Code', 'ActionGeo_ADM2Code', 'ActionGeo_Lat', 'ActionGeo_Long', 'ActionGeo_FeatureID', 'DATEADDED', 'SOURCEURL']
(10, 61)

### 2.2 **Analyize Daily**

In [15]:
daily.sample(5)

           Date   AvgTone  AvgGoldstein  EventCount  TotalMentions
948  2020-08-06 -2.268441      0.759019      212816        1254448
292  2018-10-20 -2.070073      0.459252      191151        1100463
1080 2020-12-16 -1.701677      0.803552      198284        1195982
2222 2024-02-01 -1.981465      0.541122      232163        1336178
2923 2026-01-02 -2.253803      0.276314      116461         680029

In [16]:
print(daily.columns.tolist())
print(daily.shape)

['Date', 'AvgTone', 'AvgGoldstein', 'EventCount', 'TotalMentions']
(3095, 5)

In [21]:
print(daily.info())
print(daily.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           3095 non-null   datetime64[ns]
 1   AvgTone        3095 non-null   float64
 2   AvgGoldstein   3095 non-null   float64
 3   EventCount     3095 non-null   int64
 4   TotalMentions  3095 non-null   int64
dtypes: datetime64[ns](1), float64(2), int64(2)
memory usage: 121.0 KB
None
                      Date      AvgTone  AvgGoldstein     EventCount  \
count                 3095  3095.000000   3095.000000    3095.000000
mean   2022-03-28 00:00:00    -1.953529      0.572571  190411.930210
min    2018-01-01 00:00:00    -3.308618     -1.579137     797.000000
25%    2020-02-13 12:00:00    -2.084356      0.483544  149077.000000
50%    2022-03-28 00:00:00    -1.938529      0.598118  191151.000000
75%    2024-05-09 12:00:00    -1.806410      0.687381  225194.500000
max    2026-06-22 00:00:00    -0.814426      1.525684  359262.000000
std                    NaN     0.236111      0.193909   57055.939833

       TotalMentions
count   3.095000e+03
mean    1.104378e+06
min     3.957000e+03
25%     8.638370e+05
50%     1.110964e+06
75%     1.296047e+06
max     2.059596e+06
std     3.301219e+05

### 2.3 **Master data analysis**

In [22]:
master.sample(5)

,Date,AvgTone,AvgGoldstein,EventCount,TotalMentions,ProtestCount,ThreatCount,MilitaryCount,AssaultCount,FightCount,MassViolenceCount,DiplomacyCount,CooperationCount
2651,2025-04-05,-1.912243,0.630642,136352,772614,2181,2336,419,2302,7930,82,56708,13124
523,2019-06-08,-1.829607,0.653526,159276,923103,1407,2485,598,2411,9067,33,68629,13922
228,2018-08-17,-2.008444,0.636716,253296,1512734,2184,3940,871,3806,14368,201,101954,24356
2747,2025-07-10,-1.836244,0.689477,215029,1213272,1499,4042,692,3524,12891,166,89688,20909
3034,2026-04-23,-1.910855,0.563356,185448,1083089,1393,3461,581,3029,11443,70,74390,17279

In [23]:
print(master.columns.tolist())
print(master.shape)

['Date', 'AvgTone', 'AvgGoldstein', 'EventCount', 'TotalMentions', 'ProtestCount', 'ThreatCount', 'MilitaryCount', 'AssaultCount', 'FightCount', 'MassViolenceCount', 'DiplomacyCount', 'CooperationCount']
(3095, 13)

In [24]:
print(master.info())
print(master.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               3095 non-null   datetime64[ns]
 1   AvgTone            3095 non-null   float64
 2   AvgGoldstein       3095 non-null   float64
 3   EventCount         3095 non-null   int64
 4   TotalMentions      3095 non-null   int64
 5   ProtestCount       3095 non-null   int64
 6   ThreatCount        3095 non-null   int64
 7   MilitaryCount      3095 non-null   int64
 8   AssaultCount       3095 non-null   int64
 9   FightCount         3095 non-null   int64
 10  MassViolenceCount  3095 non-null   int64
 11  DiplomacyCount     3095 non-null   int64
 12  CooperationCount   3095 non-null   int64
dtypes: datetime64[ns](1), float64(2), int64(10)
memory usage: 314.5 KB
None
                      Date      AvgTone  AvgGoldstein     EventCount  \
count                 3095  3095.000000   3095.000000    3095.000000
mean   2022-03-28 00:00:00    -1.953529      0.572566  190412.673667
min    2018-01-01 00:00:00    -3.308618     -1.579137     797.000000
25%    2020-02-13 12:00:00    -2.084356      0.483544  149077.000000
50%    2022-03-28 00:00:00    -1.938529      0.598118  191151.000000
75%    2024-05-09 12:00:00    -1.806410      0.687381  225194.500000
max    2026-06-22 00:00:00    -0.814426      1.525684  359262.000000
std                    NaN     0.236121      0.193922   57054.738727

       TotalMentions  ProtestCount  ThreatCount  MilitaryCount  AssaultCount  \
count   3.095000e+03   3095.000000  3095.000000    3095.000000   3095.000000
mean    1.104382e+06   1950.312439  3120.856543     694.419386   3050.433926
min     3.957000e+03      2.000000     7.000000       0.000000      8.000000
25%     8.638370e+05   1476.000000  2427.500000     536.500000   2375.500000
50%     1.110964e+06   1836.000000  3117.000000     676.000000   2949.000000
75%     1.296047e+06   2372.000000  3743.500000     815.000000   3713.000000
max     2.059596e+06  10128.000000  8979.000000    2400.000000   6966.000000
std     3.301155e+05    746.225914   965.913361     242.112529   1001.899740

         FightCount  MassViolenceCount  DiplomacyCount  CooperationCount
count   3095.000000        3095.000000     3095.000000       3095.000000
mean   11891.938611          94.544426    77262.084330      18175.094669
min       42.000000           0.000000      335.000000         70.000000
25%     9758.000000          51.000000    60732.500000      14046.500000
50%    11644.000000          78.000000    76935.000000      18388.000000
75%    14084.500000         119.000000    91476.000000      22179.500000
max    27934.000000         879.000000   151018.000000      36395.000000
std     3344.388441          66.957332    23896.468807       5556.093203

### 2.4 **Country Conflict Analysis**

In [25]:
conflict.sample(5)

,Date,USA_Conflict,India_Conflict,China_Conflict,Russia_Conflict,Pakistan_Conflict,Israel_Conflict,Iran_Conflict
2756,2025-07-19,2447,470,208,1209,425,1431,300
14,2018-01-15,4613,573,372,980,732,1361,475
2225,2024-02-04,3347,156,204,1314,210,2141,940
2113,2023-10-15,2689,224,308,1329,132,8567,889
121,2018-05-02,5821,501,327,716,388,982,903

In [27]:
print(conflict.columns.tolist())
print(conflict.shape)

['Date', 'USA_Conflict', 'India_Conflict', 'China_Conflict', 'Russia_Conflict', 'Pakistan_Conflict', 'Israel_Conflict', 'Iran_Conflict']
(3095, 8)

In [28]:
print(conflict.info())
print(conflict.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               3095 non-null   datetime64[ns]
 1   USA_Conflict       3095 non-null   int64
 2   India_Conflict     3095 non-null   int64
 3   China_Conflict     3095 non-null   int64
 4   Russia_Conflict    3095 non-null   int64
 5   Pakistan_Conflict  3095 non-null   int64
 6   Israel_Conflict    3095 non-null   int64
 7   Iran_Conflict      3095 non-null   int64
dtypes: datetime64[ns](1), int64(7)
memory usage: 193.6 KB
None
                      Date  USA_Conflict  India_Conflict  China_Conflict  \
count                 3095   3095.000000     3095.000000     3095.000000
mean   2022-03-28 00:00:00   3949.307916      311.826494      395.193215
min    2018-01-01 00:00:00     16.000000        0.000000        0.000000
25%    2020-02-13 12:00:00   3012.000000      228.000000      276.000000
50%    2022-03-28 00:00:00   3886.000000      292.000000      370.000000
75%    2024-05-09 12:00:00   4706.500000      372.000000      468.500000
max    2026-06-22 00:00:00  12295.000000     1372.000000     2235.000000
std                    NaN   1391.179304      128.831497      184.546319

       Russia_Conflict  Pakistan_Conflict  Israel_Conflict  Iran_Conflict
count      3095.000000        3095.000000      3095.000000    3095.000000
mean       1404.548627         291.207431      1284.228110     541.650081
min           0.000000           0.000000         2.000000       2.000000
25%         671.000000         182.000000       492.000000     208.000000
50%        1247.000000         236.000000       801.000000     302.000000
75%        1899.500000         313.000000      1596.000000     510.000000
max       12612.000000        6660.000000     13668.000000   13863.000000
std         962.537539         283.648869      1348.416423     922.453921

### 2.5 **Country Event Analyize**

In [30]:
events.sample(5)

,Date,USA_Events,China_Events,Russia_Events,India_Event,Pakistan_Events,Israel_Events,Iran_Events
611,2019-09-04,54204,8091,9742,3354,3749,4517,5810
587,2019-08-11,28290,4106,3605,2735,2694,3281,1587
1971,2023-05-26,44338,7149,17145,3306,2236,2381,2457
1947,2023-05-02,50441,6723,12114,3475,2362,6558,2193
2269,2024-03-19,46745,6916,12940,3525,2456,11867,1444

In [31]:
print(events.columns.tolist())
print(events.shape)

['Date', 'USA_Events', 'China_Events', 'Russia_Events', 'India_Event', 'Pakistan_Events', 'Israel_Events', 'Iran_Events']
(3095, 8)

In [32]:
print(events.info())
print(events.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             3095 non-null   datetime64[ns]
 1   USA_Events       3095 non-null   int64
 2   China_Events     3095 non-null   int64
 3   Russia_Events    3095 non-null   int64
 4   India_Event      3095 non-null   int64
 5   Pakistan_Events  3095 non-null   int64
 6   Israel_Events    3095 non-null   int64
 7   Iran_Events      3095 non-null   int64
dtypes: datetime64[ns](1), int64(7)
memory usage: 193.6 KB
None
                      Date    USA_Events  China_Events  Russia_Events  \
count                 3095   3095.000000   3095.000000    3095.000000
mean   2022-03-28 00:00:00  38454.347011   5470.189661    9544.016155
min    2018-01-01 00:00:00    259.000000     15.000000      17.000000
25%    2020-02-13 12:00:00  28506.000000   3892.500000    6365.500000
50%    2022-03-28 00:00:00  38697.000000   5190.000000    9003.000000
75%    2024-05-09 12:00:00  46346.500000   6861.500000   11795.000000
max    2026-06-22 00:00:00  84156.000000  22396.000000   59805.000000
std                    NaN  13332.587210   2243.984361    4792.159533

       India_Event  Pakistan_Events  Israel_Events   Iran_Events
count  3095.000000      3095.000000    3095.000000   3095.000000
mean   2564.654927      2154.738934    5763.375121   3051.803554
min       5.000000         3.000000      28.000000     31.000000
25%    2026.000000      1574.500000    3099.000000   1595.000000
50%    2597.000000      1913.000000    4485.000000   2201.000000
75%    3063.000000      2436.000000    6995.000000   3319.000000
max    6260.000000     18252.000000   45465.000000  39176.000000
std     718.958727      1105.375059    4455.604068   3061.619710

### 2.6 **Country Tone Analysis**

In [33]:
tone.sample(5)

,Date,USA_Tone,China_Tone,Russia_Tone,Pakistan_Tone,Israel_Tone,India_Tone,Iran_Tone
1253,2021-06-07,-1.716148,-1.702904,-2.186941,-3.379673,-3.183849,-2.291097,-2.881093
366,2019-01-02,-1.909587,-0.736685,-2.730328,-2.438662,-2.036825,-2.364637,-2.479752
31,2018-02-01,-1.978551,-0.279986,-2.247313,-3.198422,-3.081099,-1.665148,-2.558503
1818,2022-12-24,-2.058786,-1.553204,-2.873951,-3.348309,-1.700618,-1.999858,-4.652210
119,2018-04-30,-1.733272,-0.603997,-2.177670,-2.607561,-2.721179,-2.021798,-2.996265

In [34]:
print(tone.columns.tolist())
print(tone.shape)

['Date', 'USA_Tone', 'China_Tone', 'Russia_Tone', 'Pakistan_Tone', 'Israel_Tone', 'India_Tone', 'Iran_Tone']
(3095, 8)

In [35]:
print(tone.info())
print(tone.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           3095 non-null   datetime64[ns]
 1   USA_Tone       3095 non-null   float64
 2   China_Tone     3095 non-null   float64
 3   Russia_Tone    3095 non-null   float64
 4   Pakistan_Tone  3095 non-null   float64
 5   Israel_Tone    3095 non-null   float64
 6   India_Tone     3095 non-null   float64
 7   Iran_Tone      3095 non-null   float64
dtypes: datetime64[ns](1), float64(7)
memory usage: 193.6 KB
None
                      Date     USA_Tone   China_Tone  Russia_Tone  \
count                 3095  3095.000000  3095.000000  3095.000000
mean   2022-03-28 00:00:00    -2.072237    -1.126260    -2.594198
min    2018-01-01 00:00:00    -4.617247    -3.553360    -7.038074
25%    2020-02-13 12:00:00    -2.215187    -1.524997    -2.985859
50%    2022-03-28 00:00:00    -2.062372    -1.053743    -2.561970
75%    2024-05-09 12:00:00    -1.907381    -0.617143    -2.149016
max    2026-06-22 00:00:00    -0.444282     1.217875    -0.450692
std                    NaN     0.282266     0.717764     0.603998

       Pakistan_Tone  Israel_Tone   India_Tone    Iran_Tone
count    3095.000000  3095.000000  3095.000000  3095.000000
mean       -2.425433    -3.284789    -2.090604    -3.196954
min        -7.232528    -6.876244    -5.367661    -6.994458
25%        -2.959152    -4.146273    -2.483026    -3.781256
50%        -2.372050    -3.180702    -2.084433    -3.152325
75%        -1.847208    -2.504762    -1.706618    -2.541640
max         3.353671     0.600324     1.073620     0.329951
std         0.870457     1.078236     0.631482     0.964934

"gdelt_daily_2018_2026.csv"
SELECT
  DATE(PARSE_DATE('%Y%m%d', CAST(SQLDATE AS STRING))) AS Date,

  AVG(AvgTone) AS AvgTone,

  AVG(GoldsteinScale) AS AvgGoldstein,

  COUNT(*) AS EventCount,

  SUM(NumMentions) AS TotalMentions

FROM `gdelt-bq.gdeltv2.events`

WHERE SQLDATE BETWEEN 20180101 AND 20260622

GROUP BY Date

ORDER BY Date

"gdelt_master_features.csv"
SELECT
  DATE(PARSE_DATE('%Y%m%d', CAST(SQLDATE AS STRING))) AS Date,

  AVG(AvgTone) AS AvgTone,
  AVG(GoldsteinScale) AS AvgGoldstein,

  COUNT(*) AS EventCount,
  SUM(NumMentions) AS TotalMentions,

  SUM(CASE WHEN EventRootCode='14' THEN 1 ELSE 0 END) AS ProtestCount,
  SUM(CASE WHEN EventRootCode='13' THEN 1 ELSE 0 END) AS ThreatCount,
  SUM(CASE WHEN EventRootCode='15' THEN 1 ELSE 0 END) AS MilitaryCount,
  SUM(CASE WHEN EventRootCode='18' THEN 1 ELSE 0 END) AS AssaultCount,
  SUM(CASE WHEN EventRootCode='19' THEN 1 ELSE 0 END) AS FightCount,
  SUM(CASE WHEN EventRootCode='20' THEN 1 ELSE 0 END) AS MassViolenceCount,

  SUM(CASE WHEN EventRootCode IN ('03','04','05') THEN 1 ELSE 0 END)
      AS DiplomacyCount,

  SUM(CASE WHEN EventRootCode IN ('06','07','08') THEN 1 ELSE 0 END)
      AS CooperationCount

FROM `gdelt-bq.gdeltv2.events`

WHERE SQLDATE BETWEEN 20180101 AND 20260622

GROUP BY Date
ORDER BY Date

"gdelt_country_events.csv"
SELECT
 DATE(PARSE_DATE('%Y%m%d', CAST(SQLDATE AS STRING))) AS Date,

 SUM(CASE WHEN Actor1CountryCode='USA'
      OR Actor2CountryCode='USA'
      THEN 1 ELSE 0 END) AS USA_Events,

 SUM(CASE WHEN Actor1CountryCode='CHN'
      OR Actor2CountryCode='CHN'
      THEN 1 ELSE 0 END) AS China_Events,

 SUM(CASE WHEN Actor1CountryCode='RUS'
      OR Actor2CountryCode='RUS'
      THEN 1 ELSE 0 END) AS Russia_Events,

 SUM(CASE WHEN Actor1CountryCode='PAK'
      OR Actor2CountryCode='PAK'
      THEN 1 ELSE 0 END) AS Pakistan_Events,

 SUM(CASE WHEN Actor1CountryCode='ISR'
      OR Actor2CountryCode='ISR'
      THEN 1 ELSE 0 END) AS Israel_Events,
 
 SUM(CASE WHEN Actor1CountryCode='IND'
      OR Actor2CountryCode='IND'
      THEN 1 ELSE 0 END) AS India_Events,

 SUM(CASE WHEN Actor1CountryCode='IRN'
      OR Actor2CountryCode='IRN'
      THEN 1 ELSE 0 END) AS Iran_Events

FROM `gdelt-bq.gdeltv2.events`
WHERE SQLDATE BETWEEN 20180101 AND 20260622
GROUP BY Date
ORDER BY Date

SELECT
 DATE(PARSE_DATE('%Y%m%d', CAST(SQLDATE AS STRING))) AS Date,

 AVG(
   CASE WHEN
      Actor1CountryCode='USA'
      OR Actor2CountryCode='USA'
   THEN AvgTone END
 ) AS USA_Tone,

 AVG(
   CASE WHEN
      Actor1CountryCode='CHN'
      OR Actor2CountryCode='CHN'
   THEN AvgTone END
 ) AS China_Tone,

 AVG(
   CASE WHEN
      Actor1CountryCode='RUS'
      OR Actor2CountryCode='RUS'
   THEN AvgTone END
 ) AS Russia_Tone,

 AVG(
   CASE WHEN
      Actor1CountryCode='PAK'
      OR Actor2CountryCode='PAK'
   THEN AvgTone END
 ) AS Pakistan_Tone,

 AVG(
   CASE WHEN
      Actor1CountryCode='ISR'
      OR Actor2CountryCode='ISR'
   THEN AvgTone END
 ) AS Israel_Tone,

 AVG(
   CASE WHEN
      Actor1CountryCode='IND'
      OR Actor2CountryCode='IND'
   THEN AvgTone END
 ) AS India_Tone,

 AVG(
   CASE WHEN
      Actor1CountryCode='IRN'
      OR Actor2CountryCode='IRN'
   THEN AvgTone END
 ) AS Iran_Tone

FROM `gdelt-bq.gdeltv2.events`

WHERE SQLDATE BETWEEN 20180101 AND 20260622

GROUP BY Date
ORDER BY Date


"gdelt_country_conflict.csv"
SELECT
 DATE(PARSE_DATE('%Y%m%d', CAST(SQLDATE AS STRING))) AS Date,

 -- USA
 SUM(
   CASE WHEN
      (Actor1CountryCode='USA'
       OR Actor2CountryCode='USA')
       AND EventRootCode IN ('13','14','15','18','19','20')
   THEN 1 ELSE 0 END
 ) AS USA_Conflict,

 -- India
 SUM(
   CASE WHEN
      (Actor1CountryCode='IND'
       OR Actor2CountryCode='IND')
       AND EventRootCode IN ('13','14','15','18','19','20')
   THEN 1 ELSE 0 END
 ) AS India_Conflict,

 -- China
 SUM(
   CASE WHEN
      (Actor1CountryCode='CHN'
       OR Actor2CountryCode='CHN')
       AND EventRootCode IN ('13','14','15','18','19','20')
   THEN 1 ELSE 0 END
 ) AS China_Conflict,

 -- Russia
 SUM(
   CASE WHEN
      (Actor1CountryCode='RUS'
       OR Actor2CountryCode='RUS')
       AND EventRootCode IN ('13','14','15','18','19','20')
   THEN 1 ELSE 0 END
 ) AS Russia_Conflict,

 -- Pakistan
 SUM(
   CASE WHEN
      (Actor1CountryCode='PAK'
       OR Actor2CountryCode='PAK')
       AND EventRootCode IN ('13','14','15','18','19','20')
   THEN 1 ELSE 0 END
 ) AS Pakistan_Conflict,

 -- Israel
 SUM(
   CASE WHEN
      (Actor1CountryCode='ISR'
       OR Actor2CountryCode='ISR')
       AND EventRootCode IN ('13','14','15','18','19','20')
   THEN 1 ELSE 0 END
 ) AS Israel_Conflict,

 -- Iran
 SUM(
   CASE WHEN
      (Actor1CountryCode='IRN'
       OR Actor2CountryCode='IRN')
       AND EventRootCode IN ('13','14','15','18','19','20')
   THEN 1 ELSE 0 END
 ) AS Iran_Conflict

FROM `gdelt-bq.gdeltv2.events`

WHERE SQLDATE BETWEEN 20180101 AND 20260622

GROUP BY Date

ORDER BY Date